---
driver_plugin: vagrant
  
platforms:
- name: ubuntu-12.04
  driver_config:
    require_chef_omnibus: "11.6.0"
    box: ubuntu-base
    box_url: http://files.vagrantup.com/precise32.box
    

suites:
- name: default
  run_list: ["recipe[artifactory::default]"]
