---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: "11.6.0"
  box: precise64
  box_url: http://files.vagrantup.com/precise64.box
  network:
  - ["private_network", {ip: "192.168.33.33"}]
  customize:
    memory: 2048
  
platforms:
- name: ubuntu-12.04

suites:
- name: artifactory
  run_list: ["recipe[artifactory]"]
