---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: "11.6.0"
  box: ubuntu-base
  box_url: http://files.vagrantup.com/precise32.box
  
platforms:
- name: ubuntu-12.04

suites:
- name: artifactory
  run_list: ["recipe[artifactory]"]
